CREATE OR REPLACE FUNCTION gen_random_string(_min_length INT = 3)
RETURNS VARCHAR
LANGUAGE SQL
AS '
SELECT substring(
  md5(random()::TEXT),
  0,
  _min_length + floor(random() * 10 + 1)::INT
)
';

COMMENT ON FUNCTION gen_random_string IS 'Generates from 3 to 3 + 10 random characters';

-- Test it
CREATE TABLE random_strings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  string VARCHAR,
  PRIMARY KEY (id)
);

DO
$do$
BEGIN
  FOR index IN 1..100000000 LOOP
    INSERT INTO random_strings (string)
    SELECT gen_random_string();
  END LOOP;
END
$do$;